baseURL = 'https://bayesianops.com/'
languageCode = 'en-us'
title = 'hello@bayesianops.com'
theme = "hello-friend-ng"

[params]
  homeSubtitle = ""

  description = "Bayesian Ops"
  keywords = "Bayesian, ops"

[params.logo]
  logoCursorDisabled = true
  logoText = " "
  logoMark = " "
